### Create a new USer
POST http://localhost:4300/auth/signup
Content-Type: application/json

{
    "email": "devsession@mub.com",
    "password": "pwd123"
    
}

### Login in with hash
POST http://localhost:4300/auth/signin
Content-Type: application/json

{
    "email": "devsafe@mub.com",
    "password": "pwd123"
}

### Incorrect format for create user
POST http://localhost:4300/auth/signup
Content-Type: application/json

{
    "email": "test",
    "password": "kjfhgkjdflgsd"
}

### Find a particular user with a given ID
GET http://localhost:4300/auth/1

### Find all users with a given email
GET http://localhost:4300/auth?email=dev@mub.com

### Delete user with a given id
DELETE http://localhost:4300/auth/14563

### Update a user
PATCH http://localhost:4300/auth/254
Content-Type: application/json

{
    "password": "password456"
}


### Get current logged in user
GET http://localhost:4300/auth/whoami 

### Sign out
POST http://localhost:4300/auth/signout